#! /bin/sh -Ceu
# backup-mirror - copy backup directories and do related tasks
###########################################################################
# backup-mirror 0.0.20220615
#
# Copyright (C) 2010-2022 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
# Try to be nice.
{
	ionice -c 3  -p "${$}"
	renice -n 99 -p "${$}"
} > /dev/null 2>&1 || :

# Locate the script.
me=$( command -v -- "${0}" || ls -d -- "${0}" )
me_base=$( basename -- "${me}" )
me_dir=$( dirname -- "${me}" )
case ${me_dir} in
.  ) dir=.. ;;
.. ) dir=../.. ;;
*. ) dir=$( cd -- "${me_dir}/.." && pwd ) ;;
*  ) dir=$( dirname -- "${me_dir}" ) ;;
esac

valid='[:alnum:]_.-'


# Parse options.
while :
do
	case ${1-} in
	--help | -h )
		COLUMNS=${COLUMNS:-$( tput cols 2> /dev/null || : )}
		exec fmt -s ${COLUMNS:+ -w "${COLUMNS}" } << __HELP__ \
		| exec sed -e '/\\$/{N;s/\\\n  *//;}'; exit
Usage: \\
           ${me_base} [<RSYNC-OPTION>]...
 or:   \\
           ${me_base} <OPTION>...

Read mirror sources from configuration files, \
copy backup directories from the mirror sources using rsync(1) and \
then delete old backup directories \
based on pattern matching and ages. \
For details, see \
${me_base%backup*}backup-mirror-sources(1) and \
${me_base%backup*}backup-purge(1).

Options:
    -h, --help[=<FORMAT>]
        Show this help message and exit.
    -V, --version
        Show version information and exit.

Rsync options:
$( exec rsync --help | exec sed '
	/^ *-/,/^$/!d
	/^ *--help/d
	/^ *--version/d
	/./!d
	s/^ */        /
	s/,-/, -/g
	/^ *-/{
		s//    -/
		s/\([^, ]\)  */'"\1\\
        "'/
	}
' )

Files:
    ${dir}/<YEAR>
        A yearly backup directory.
    ${dir}/<YEAR>[-]<MONTH>
        A monthly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>
        A weekly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>
        An hourly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>T<HOUR>
        An hourly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>
        A minutely backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>T<HOUR>[:]<MINUTE>
        A minutely backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>[:]<SECOND>
        A secondly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>T<HOUR>[:]<MINUTE>[:]<SECOND>
        A secondly backup directory.
    ${dir}/latest
        A symbolic link to the latest backup directory.
    ${dir}/conf/copy-config
        An optional configuration file \
used by ${me_base%backup*}backup-copy-rsync(1) \
used by ${me_base%backup*}backup-copy(1) \
used by ${me_base%backup*}backup-mirror-sources(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1) \
when copying a backup directory.
    ${dir}/conf/mirror-src-base
        An optional configuration file \
used by ${me_base%backup*}backup-mirror-sources(1) \
containing the mirror source base directory \
to be used to augment \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <BASE-DIR>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-host
        An optional configuration file \
used by ${me_base%backup*}backup-mirror-sources(1) \
containing the mirror source host \
to be used to augment \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <HOST>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-list
        A configuration file \
used by ${me_base%backup*}backup-mirror-sources(1) \
containing the mirror sources \
to be copied to newly created backup directories \
when copying backup directories. \
The file must contain operand lines having any the following forms:
            <SRC>/[.]
                A local directory containing backup directories to be copied.
            <SRC>
                A local backup directory to be copied.
            [<USER>@]<HOST>:<SRC>/[.]
                A remote directory containing backup directories to be copied via a remote shell.
            [<USER>@]<HOST>:<SRC>
                A remote backup directory to be copied via a remote shell.
            [<USER>@]<HOST>::<MODULE>[/<SRC>]/[.]
                A remote directory containing backup directories to be copied via an rsync daemon.
            [<USER>@]<HOST>::<MODULE>/<SRC>
                A remote backup directory to be copied via an rsync daemon.
            rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>[/<SRC>]/[.]
                A remote directory containing backup directories to be copied via an rsync daemon.
            rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>/<SRC>
                A remote backup directory to be copied via an rsync daemon.
        The operands specifying directories containing backup directories \
will be passed \
to the ${me_base%backup*}backup-rsync(1) tool. \
The backup directories within these directories \
as well as the operands specifying backup directories \
will be passed \
to the ${me_base%backup*}backup-copy(1) tool. \
Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-list.d
        An optional directory \
used by ${me_base%backup*}backup-mirror-sources(1) \
containing configuration files \
similar to the ${dir}/conf/mirror-src-list configuration file \
containing the mirror sources \
to be copied to a newly created backup directory \
when copying backup directories. \
The names of the files must consist of only characters \
matching the pattern [${valid}].
    ${dir}/conf/mirror-src-module
        An optional configuration file \
used by ${me_base%backup*}backup-mirror-sources(1) \
containing the mirror source module \
to be used to augment \
the mirror source host specified in the conf/mirror-src-host configuration file and \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <MODULE>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-port
        An optional configuration file \
used by ${me_base%backup*}backup-mirror-sources(1) \
containing the mirror source port \
to be used to augment \
the mirror source host specified in the conf/mirror-src-host configuration file, \
the mirror source module specified in the conf/mirror-src-module configuration file and \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <PORT>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-prefix
        An optional configuration file \
used by ${me_base%backup*}backup-mirror-sources(1) \
containing the mirror source prefix \
to be used to augment \
the mirror sources specified in the conf/mirror-src-list configuration file. \
The file must contain a line having one of the following forms:
            <BASE-DIR>
                A local base directory.
            [<USER>@]<HOST>:[<BASE-DIR>]
                A remote shell host and an optional base directory.
            [<USER>@]<HOST>::[<MODULE>[/<BASE-DIR>]]
                An rsync daemon host and an optional module and base directory.
            <USER>@
                A remote shell or an rsync daemon user.
            rsync://[<USER>@]<HOST>[:<PORT>][/<MODULE>[/<BASE-DIR>]]
                An rsync daemon host and an optional module and base directory.
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-user
        An optional configuration file \
used by ${me_base%backup*}backup-mirror-sources(1) \
containing the mirror source user \
to be used to augment \
the mirror source host specified in the conf/mirror-src-host configuration file and \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <USER>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/purge-list
        An optional configuration file \
used by ${me_base%backup*}backup-purge(1) \
containing patterns and ages \
which override the default ones. \
The file must contain operand lines having the following form:
            <PATTERN>=<DAYS>
        Empty lines and comment lines (starting with a "#") are allowed, too. \
Backup directories matching <PATTERN> are deleted \
if they are over <DAYS> days old.
    ${dir}/conf/rsh
        An optional script \
to be used as a remote shell instead of the plain ssh(1). \
This script can be used for setting identity files and proxy commands, \
for instance.
    ${dir}/conf/rsync-config
        An optional configuration file \
used by ${me_base%backup*}backup-rsync(1) \
used by ${me_base%backup*}backup-copy-rsync(1) and ${me_base%backup*}backup-create-rsync(1) \
used by ${me_base%backup*}backup-copy(1) and ${me_base%backup*}backup-create(1) \
used by ${me_base%backup*}backup-mirror-sources(1) and ${me_base%backup*}backup-sources(1) \
used by ${me_base%backup*}backup(1) and ${me_base}(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1).
    ${dir}/tmp/
        A temporary directory to be used for copying backup directories.
    ${dir}/tools/${me_base%backup*}backup-mirror-sources
        Used for copying backup directories from mirror sources using rsync(1).
    ${dir}/tools/${me_base%backup*}backup-purge
        Used for deleting old backup directories \
based on pattern matching and ages.

See also:
    ${me_base%backup*}backup-help(1),
    ${me_base%backup*}backup-mirror-sources(1),
    ${me_base%backup*}backup-purge(1)

    rsync(1),
    ssh(1)

    Home page <https://github.Eero.Häkkinen.fi/rsync-backup/>
__HELP__
		;;
	--help=* | --version | -V )
		export BACKUP_TOOL="${0}"
		exec "${0%backup*}backup-help" "${1}"
		;;
	esac
	break
done

# Copy backup directories from mirror sources.
"${0%backup*}backup-mirror-sources" "${@}"

# Delete old backup directories.
"${0%backup*}backup-purge"
