#! /bin/sh -Ceu
###########################################################################
# backup 0.0.20121212
#
# Copyright (C) 2010-2012 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
# Try to be nice.
{
	ionice -c 3  -p "${$}"
	renice -n 10 -p "${$}"
} > /dev/null 2>&1 || :

# Locate the script.
me=$( which -- "${0}" || ls -d -- "${0}" )
dir=$( dirname -- "${me}" )
case ${dir} in
. ) dir=.. ;;
* ) dir=$( dirname -- "${dir}" ) ;;
esac

short_description='create backups and do related tasks'
valid=[:alnum:]_.-

case ${1-} in
--help | -h ) exec fmt -s -w "${COLUMNS:-$( tput cols )}" << __HELP__
Usage: ${0##*[\\/]} [<RSYNC-OPTION>]...
 or:   ${0##*[\\/]} <OPTION>...

Prepare for backups, create backups and then delete old backup directories. \
For details, see \
${0##*[\\/]}-prepare(1), \
${0##*[\\/]}-create(1) and \
${0##*[\\/]}-purge(1).

Options:
    -h, --help[=<FORMAT>]
        Show this help message and exit.
    -V, --version
        Show version information and exit.

Rsync options:
$( rsync --help | sed '
	/^ *-/,/^$/!d
	/ --help/d
	/ --version/d
	/./!d
	s/^ */        /
	s/,-/, -/g
	/^ *-/{
		s//    -/
		s/\([^, ]\) /\1\
/
	}
	P
	D
' )

Files:
    ${dir}/<YEAR>
        A yearly backup directory.
    ${dir}/<YEAR>[-]<MONTH>
        A monthly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>
        A weekly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>
        An hourly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>
        A minutely backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>[:]<SECOND>
        A secondly backup directory.
    ${dir}/latest
        A symbolic link to the latest backup directory.
    ${dir}/conf/pre.d/
        An optional directory containing scripts \
which are executed in lexical order of names \
when preparing for backups. \
The names of the files must consist of only characters \
matching the pattern [${valid}].
    ${dir}/conf/purge-list
        An optional file to override the default patterns and ages. \
The file must contain operand lines having the following form:
            <PATTERN>=<DAYS>
        These operands will be passed \
to the ${dir}/tools/${0##*[\\/]}-purge(1) tool. \
Empty lines and comment lines (starting with a "#") are allowed, too. \
Backup directories matching <PATTERN> are deleted \
if they are over <DAYS> day old.
    ${dir}/conf/rsh
        An optional script \
to be used as a remote shell instead of the plain ssh(1). \
This script can be used for setting identity files and proxy commands, \
for instance.
    ${dir}/conf/src-list
        A file to specify the sources to be used when creating backups. \
The file must contain operand lines having the following form:
            [[<USER>@]<HOST>:]<SRC>
        These operands will be passed \
to the ${dir}/tools/${0##*[\\/]}-create(1) tool. \
Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/tag-formats
        An optional file containing date formats \
to be used when constructing backup directory names for backups. \
Empty lines and comment lines (starting with a "#") are allowed, too. \
Each date format is tried in turn in order specified \
until a non-existing backup directory is found.
    ${dir}/tmp/
        A temporary directory to be used for creating new backup directories.
    <SOURCE-DIRECTORY>/.backup-filter
        An optional per-directory rsync(1) filter merge-file \
which can be used for excluding files from backups. \
Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/tools/${0##*[\\/]}-create
        Used for creating backups using rsync(1).
    ${dir}/tools/${0##*[\\/]}-prepare
        Used for preparing for backups by executing preparation scripts.
    ${dir}/tools/${0##*[\\/]}-purge
        Used for deleting old backup directories \
based on pattern matching and age.
    $( which rsync )
        A fast and extraordinarily versatile file copying tool. \
See also rsync(1).
    $( which ssh )
        A remote login program. See also ssh(1)
__HELP__
;;
--help=help2man )
	COLUMNS=2500 exec "${0}" --help \
	| exec sed \
		-e '/^    [^ ]/!b'	\
		-e 'N'			\
		-e 's/\n        /  /'	\
		-e 'P'			\
		-e 'D'
	exit
	;;
--help=man )
	exec "${0}" --help=troff \
	| exec man -l -- -
	exit
	;;
--help=troff )
	exec help2man -h --help=help2man -L en_US.UTF-8 -N -n "${short_description}" -- "${0}"
	;;
--version | -V )
	exec sed -n \
		-e '/^[^#]/q'			\
		-e 's/^#\( \(.*\)\)*$/\2/p'	\
		-e '/^##/{2!q;}'		\
		-- "${me}"
	;;
esac

# Prepare for backups.
"${0%backup}backup-prepare"

# Create backups.
set -- "${@}" --
while read arg
do
	case ${arg} in
	'' | '#'* ) continue ;;
	esac
	set -- "${@}" "${arg}"
done < "${dir}/conf/src-list"
"${0%backup}backup-create" "${@}"

# Delete old backup directories.
if [ -f "${dir}/conf/purge-list" ]
then
	set -- --
	while read arg
	do
		case ${arg} in
		'' | '#'* ) continue ;;
		esac
		set -- "${@}" "${arg}"
	done < "${dir}/conf/purge-list"
else
	set --
fi
case ${#},${1-} in
1,-- ) ;;
*,*  ) "${0%backup}backup-purge" "${@}" ;;
esac
