#! /bin/sh -Ceu
###########################################################################
# backup-sources 0.0.20211107
#
# Copyright (C) 2010-2021 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
# Try to be nice.
{
	ionice -c 3  -p "${$}"
	renice -n 99 -p "${$}"
} > /dev/null 2>&1 || :

# Locate the script.
me=$( command -v -- "${0}" || ls -d -- "${0}" )
me_dir=$( dirname -- "${me}" )
case ${me_dir} in
. ) dir=.. ;;
* ) dir=$( dirname -- "${me_dir}" ) ;;
esac

basename=${0##*[\\/]}
short_description='create a new backup directory from backup sources'



# Parse options.
while :
do
	case ${1-} in
	--help | -h )
		COLUMNS=${COLUMNS:-$( tput cols 2> /dev/null || : )}
		exec fmt -s ${COLUMNS:+ -w "${COLUMNS}" } << __HELP__ \
		| exec sed -e '/\\$/{N;s/\\\n  *//;}'; exit
Usage: \\
           ${basename} [<RSYNC-OPTION>]...
 or:   \\
           ${basename} <OPTION>...

Read backup sources from configuration files and \
create a new backup directory from the backup sources using rsync(1). \
For details, see \
the Files section and \
${basename%backup*}backup-create(1).

The newly created backup directory \
is named according to the backup date and time and \
is a full backup directory \
containing direct (but possible filtered) copies \
of original files and directories. \
It can thus be accessed and restored directly.

Options:
    -h, --help[=<FORMAT>]
        Show this help message and exit.
    -V, --version
        Show version information and exit.

Rsync options:
$( exec rsync --help | exec sed '
	/^ *-/,/^$/!d
	/^ *--help/d
	/^ *--version/d
	/./!d
	s/^ */        /
	s/,-/, -/g
	/^ *-/{
		s//    -/
		s/\([^, ]\)  */\1\
        /
	}
' )

Files:
    ${dir}/<YEAR>
        A yearly backup directory.
    ${dir}/<YEAR>[-]<MONTH>
        A monthly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>
        A weekly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>
        An hourly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>T<HOUR>
        An hourly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>
        A minutely backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>T<HOUR>[:]<MINUTE>
        A minutely backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>[:]<SECOND>
        A secondly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>T<HOUR>[:]<MINUTE>[:]<SECOND>
        A secondly backup directory.
    ${dir}/latest
        A symbolic link to the latest backup directory.
    ${dir}/conf/backup-src-base
        An optional configuration file \
containing the backup source base directory \
to be used to augment \
the backup sources specified in the conf/backup-src-list configuration file \
if the conf/backup-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <BASE-DIR>[/.[/]]
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/backup-src-host
        An optional configuration file \
containing the backup source host \
to be used to augment \
the backup sources specified in the conf/backup-src-list configuration file \
if the conf/backup-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <HOST>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/backup-src-list
        A configuration file \
containing the backup sources \
to be copied to a newly created backup directory \
when creating a new backup. \
The file must contain operand lines having any the following forms:
            <SRC>
                A local source to be copied to a newly created backup directory.
            <BASE-DIR>/./[<SRC>]
                A local source to be copied to a newly created backup directory without the base directory.
            [<USER>@]<HOST>:<SRC>
                A remote shell source to be copied to a newly created backup directory.
            [<USER>@]<HOST>:<BASE-DIR>/./[<SRC>]
                A remote shell source to be copied to a newly created backup directory without the base directory.
            [<USER>@]<HOST>::<MODULE>[/[<SRC>]]
                An rsync daemon source to be copied to a newly created backup directory.
            [<USER>@]<HOST>::<MODULE>/<BASE-DIR>/./[<SRC>]
                An rsync daemon source to be copied to a newly created backup directory without the base directory.
            rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>[/[<SRC>]]
                An rsync daemon source to be copied to a newly created backup directory.
            rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>/<BASE-DIR>/./[<SRC>]
                An rsync daemon source to be copied to a newly created backup directory without the base directory.
        These operands will be passed \
to the ${basename%backup*}backup-create(1) tool. \
Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/backup-src-module
        An optional configuration file \
containing the backup source module \
to be used to augment \
the backup source host specified in the conf/backup-src-host configuration file and \
the backup sources specified in the conf/backup-src-list configuration file \
if the conf/backup-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <MODULE>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/backup-src-port
        An optional configuration file \
containing the backup source port \
to be used to augment \
the backup source host specified in the conf/backup-src-host configuration file, \
the backup source module specified in the conf/backup-src-module configuration file and \
the backup sources specified in the conf/backup-src-list configuration file \
if the conf/backup-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <PORT>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/backup-src-prefix
        An optional configuration file \
containing the backup source prefix \
to be used to augment \
the backup sources specified in the conf/backup-src-list configuration file. \
The file must contain a line having one of the following forms:
            <BASE-DIR>[/.[/]]
                A local base directory.
            [<USER>@]<HOST>:[<BASE-DIR>[/.[/]]]
                A remote shell host and an optional base directory.
            [<USER>@]<HOST>::[<MODULE>[/<BASE-DIR>[/.[/]]]]
                An rsync daemon host and an optional module and base directory.
            <USER>@
                A remote shell or an rsync daemon user.
            rsync://[<USER>@]<HOST>[:<PORT>][/<MODULE>[/<BASE-DIR>[/.[/]]]]
                An rsync daemon host and an optional module and base directory.
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/backup-src-user
        An optional configuration file \
containing the backup source user \
to be used to augment \
the backup source host specified in the conf/backup-src-host configuration file and \
the backup sources specified in the conf/backup-src-list configuration file \
if the conf/backup-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <USER>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/create-config
        An optional configuration file \
used by ${basename%backup*}backup-create-rsync(1) \
used by ${basename%backup*}backup-create(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1) \
when creating a new backup directory.
    ${dir}/conf/rsh
        An optional script \
to be used as a remote shell instead of the plain ssh(1). \
This script can be used for setting identity files and proxy commands, \
for instance.
    ${dir}/conf/rsync-config
        An optional configuration file \
used by ${basename%backup*}backup-rsync(1) \
used by ${basename%backup*}backup-copy-rsync(1) and ${basename%backup*}backup-create-rsync(1) \
used by ${basename%backup*}backup-copy(1) and ${basename%backup*}backup-create(1) \
used by ${basename%backup*}backup-mirror-sources(1) and ${basename}(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1).
    ${dir}/conf/tag-formats
        An optional configuration file \
used by ${basename%backup*}backup-create(1) \
containing date formats \
to be used \
when constructing a backup directory name for a new backup. \
Empty lines and comment lines (starting with a "#") are allowed, too. \
Each date format is tried in turn in order specified \
until a non-existing backup directory is found.
    ${dir}/tmp/
        A temporary directory to be used for creating a new backup directory.
    ${dir}/tools/${basename%backup*}backup-create
        Used for creating a new backup directory from backup sources \
using rsync(1).
    <SOURCE-DIRECTORY>/.backup-filter
        An optional per-directory rsync(1) filter merge-file \
which can be used for excluding files from backups. \
Empty lines and comment lines (starting with a "#") are allowed, too.

See also:
    ${basename%backup*}backup(1),
    ${basename%backup*}backup-create(1)

    rsync(1),
    ssh(1)

    Home page <https://github.Eero.Häkkinen.fi/rsync-backup/>
__HELP__
		;;
	--help=help2man )
		COLUMNS=2500 exec "${0}" --help \
		| exec sed \
			-e '/^See also:$/,/^[^ ]/{s/^\(See also\):$/*\1*/;s/^ *//;}' \
			-e '/^    [^ ]/!b'	\
			-e '/[^ ]  /b'		\
			-e 'N'			\
			-e 's/\n        -/  ​-/'	\
			-e 's/\n        /  /'	\
			-e 'P'			\
			-e 'D'
		exit
		;;
	--help=man )
		exec "${0}" --help=troff \
		| exec man -l -- -
		exit
		;;
	--help=troff )
		cat << '__TROFF__'
.if '\*[.T]'html' \{\
.HEAD "<link href=""groff.css"" rel=""stylesheet"" type=""text/css"" />"
.HEAD "<meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />"
.HX 0
.\}
__TROFF__
		exec help2man -h --help=help2man -L en_US.UTF-8 -N -n "${short_description}" -- "${0}" \
		| exec sed \
			-e '\|^[.]B backup|,\|^[.]SH |{' \
			-e '\|^[^.]|s| |&\\%|g' \
			-e '\|^[^.]|s|^|&\\%|' \
			-e '\|^[.]br$|d' \
			-e 's|^[.]B backup|.SY backup|' \
			-e '\|^[.]SH |i\
.YS' \
			-e '}' \
			-e 's|\([[:alpha:]][[:alnum:]\\_-]*\)[(]\([[:digit:]]*\)[)]|\\fB\1\\fR(\2)|g' \
			-e 's|^\(.*\) <\(https://[^<[:space:]>]*\)>$|.UR \2\
\1\
.UE|'
		exit
		;;
	--help=* )
		exec "${0}" --help=troff \
		| exec man -l -T"${1#*=}" -- -
		exit
		;;
	--version | -V )
		exec sed -n \
			-e '/^[^#]/q'				\
			-e "3s/^# [^ ]* /# ${basename} /"	\
			-e 's/^#\( \(.*\)\)*$/\2/p'		\
			-e '/^##/{2!q;}'			\
			-- "${me}"
		;;
	esac
	break
done

# Create a new backup directory from backup sources.
set -- "${@}" --
if [ ! -f "${dir}/conf/backup-src-prefix" ]
then
	if [ ! -f "${dir}/conf/backup-src-base" ]
	then
		unset src_base
	else
		src_base=$(
			grep -- '^[^#]' "${dir}/conf/backup-src-base"
			)
		src_base=${src_base%/}/
	fi
	if [ ! -f "${dir}/conf/backup-src-host" ]
	then
		src_prefix=${src_base-}
	else
		src_prefix=$( grep -- '^[^#]' "${dir}/conf/backup-src-host" )
		[ ! -f "${dir}/conf/backup-src-user" ] || src_prefix=$(
			grep -- '^[^#]' "${dir}/conf/backup-src-user"
			)@${src_prefix}
		if [ ! -f "${dir}/conf/backup-src-module" ]
		then
			src_prefix=${src_prefix}:${src_base-}
		else
			src_module=$(
				grep -- '^[^#]' "${dir}/conf/backup-src-module"
				)
			if [ ! -f "${dir}/conf/backup-src-port" ]
			then
				src_prefix=${src_prefix}::${src_module}${src_base+/${src_base#/}}
			else
				src_port=$(
					grep -- '^[^#]' "${dir}/conf/backup-src-port"
					)
				src_prefix=rsync://${src_prefix}:${src_port}/${src_module}${src_base+/${src_base#/}}
			fi
		fi
	fi
else
	src_prefix=$( grep -- '^[^#]' "${dir}/conf/backup-src-prefix" )
fi
while read src
do
	case ${src} in
	'' | '#'* ) continue ;;
	esac
	case ${src_prefix} in
	*/ ) src=${src#/} ;;
	esac
	set -- "${@}" "${src_prefix}${src}"
done < "${dir}/conf/backup-src-list"
exec "${0%backup*}backup-create" "${@}"
