#! /bin/sh -Ceu
###########################################################################
# backup-nologin 0.0.20211218
#
# Copyright (C) 2019-2021 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
case ${SSH_ORIGINAL_COMMAND:++},${#},${1-} in
+,2,-c )
	command_string=${2#"exec "}
	case ${command_string} in
	"${0%backup*}backup-rsync "*            | \
	"sudo ${0%backup*}backup-rsync "*       | \
	"sudo -- ${0%backup*}backup-rsync "*    | \
	"sudo -n ${0%backup*}backup-rsync "*    | \
	"sudo -n -- ${0%backup*}backup-rsync "* )
		case ${command_string} in
		'sudo '* ) unset LD_PRELOAD ;;
		esac
		# shellcheck disable=SC2086
		exec \
			${command_string%%"${0%backup*}backup-rsync "*} \
			"${0%backup*}backup-rsync" \
			${command_string#*"${0%backup*}backup-rsync "}
		;;
	esac
	;;
esac
exec /usr/sbin/nologin "${@}"
