#! /bin/sh -Ceu
###########################################################################
# backup 0.0.20200510
#
# Copyright (C) 2010-2020 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
# Try to be nice.
{
	ionice -c 3  -p "${$}"
	renice -n 99 -p "${$}"
} > /dev/null 2>&1 || :

# Locate the script.
me=$( which -- "${0}" || ls -d -- "${0}" )
dir=$( dirname -- "${me}" )
case ${dir} in
. ) dir=.. ;;
* ) dir=$( dirname -- "${dir}" ) ;;
esac

basename=${0##*[\\/]}
short_description='create backups and do related tasks'
valid=[:alnum:]_.-


# Parse options.
while :
do
	case ${1-} in
	--help | -h ) exec fmt -s -w "${COLUMNS:-$( tput cols )}" << __HELP__
Usage: ${basename} [<RSYNC-OPTION>]...
 or:   ${basename} <OPTION>...

Prepare for backups, create backups and then delete old backup directories. \
For details, see \
${basename%backup*}backup-prepare(1), \
${basename%backup*}backup-create(1) and \
${basename%backup*}backup-purge(1).

Options:
    -h, --help[=<FORMAT>]
        Show this help message and exit.
    -V, --version
        Show version information and exit.

Rsync options:
$( exec rsync --help | exec sed '
	/^ *-/,/^$/!d
	/ --help/d
	/ --version/d
	/./!d
	s/^ */        /
	s/,-/, -/g
	/^ *-/{
		s//    -/
		s/\([^, ]\) /\1\
/
	}
	P
	D
' )

Files:
    ${dir}/<YEAR>
        A yearly backup directory.
    ${dir}/<YEAR>[-]<MONTH>
        A monthly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>
        A weekly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>
        An hourly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>
        A minutely backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>[:]<SECOND>
        A secondly backup directory.
    ${dir}/latest
        A symbolic link to the latest backup directory.
    ${dir}/conf/create-config
        An optional configuration file \
used by ${basename%backup*}backup-create(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1).
    ${dir}/conf/rsync-config
        An optional configuration file \
used by ${basename%backup*}backup-rsync(1) \
used by ${basename%backup*}backup-copy(1) and ${basename%backup*}backup-create(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1).
    ${dir}/conf/pre.d/
        An optional directory containing scripts \
which are executed in lexical order of names \
when preparing for backups. \
The names of the files must consist of only characters \
matching the pattern [${valid}].
    ${dir}/conf/purge-list
        An optional file to override the default patterns and ages. \
The file must contain operand lines having the following form:
            <PATTERN>=<DAYS>
        Empty lines and comment lines (starting with a "#") are allowed, too. \
Backup directories matching <PATTERN> are deleted \
if they are over <DAYS> day old.
    ${dir}/conf/rsh
        An optional script \
to be used as a remote shell instead of the plain ssh(1). \
This script can be used for setting identity files and proxy commands, \
for instance.
    ${dir}/conf/src-host
        An optional file to specify the source host \
if the source host is not specified in the conf/src-list file or in the conf/src-prefix file. \
The file must contain a line having the following form:
            [<USER>@]<HOST>
    ${dir}/conf/src-list
        A file to specify the sources \
to be copied to a newly created backup directory \
when creating backups. \
The file must contain operand lines having any the following forms:
            [[<USER>@]<HOST>:]<SRC>
            [<USER>@]<HOST>::<SRC>
            rsync://[<USER>@]<HOST>[:<PORT>]/<SRC>
        These operands will be passed \
to the ${basename%backup*}backup-create(1) tool. \
Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/src-prefix
        An optional file to specify the source prefix \
if the source prefix is not specified in the conf/src-list file. \
The file must contain a line having one of the following forms:
            <DIR>
            [<USER>@]<HOST>:[<DIR>]
            [<USER>@]<HOST>::[<MODULE>]
            rsync://[<USER>@]<HOST>[:<PORT>][/<MODULE>]
    ${dir}/conf/tag-formats
        An optional file containing date formats \
to be used when constructing backup directory names for backups. \
Empty lines and comment lines (starting with a "#") are allowed, too. \
Each date format is tried in turn in order specified \
until a non-existing backup directory is found.
    ${dir}/tmp/
        A temporary directory to be used for creating new backup directories.
    <SOURCE-DIRECTORY>/.backup-filter
        An optional per-directory rsync(1) filter merge-file \
which can be used for excluding files from backups. \
Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/tools/${basename%backup*}backup-create
        Used for creating backups using rsync(1).
    ${dir}/tools/${basename%backup*}backup-prepare
        Used for preparing for backups by executing preparation scripts.
    ${dir}/tools/${basename%backup*}backup-purge
        Used for deleting old backup directories \
based on pattern matching and age.
    $( which rsync )
        A fast and extraordinarily versatile file copying tool. \
See also rsync(1).
    $( which ssh )
        A remote login program. \
See also ssh(1).
__HELP__
		;;
	--help=help2man )
		COLUMNS=2500 exec "${0}" --help \
		| exec sed \
			-e '/^    [^ ]/!b'	\
			-e '/[^ ]  /b'		\
			-e 'N'			\
			-e 's/\n        /  /'	\
			-e 'P'			\
			-e 'D'
		exit
		;;
	--help=man )
		exec "${0}" --help=troff \
		| exec man -l -- -
		exit
		;;
	--help=troff )
		exec help2man -h --help=help2man -L en_US.UTF-8 -N -n "${short_description}" -- "${0}" \
		| exec sed -e 's/\([[:alnum:]\\-][[:alnum:]\\-]*\)[(]\([[:digit:]]*\)[)]/\\fB\1\\fR(\2)/g'
		exit
		;;
	--version | -V )
		exec sed -n \
			-e '/^[^#]/q'				\
			-e "3s/^# [^ ]* /# ${basename} /"	\
			-e 's/^#\( \(.*\)\)*$/\2/p'		\
			-e '/^##/{2!q;}'			\
			-- "${me}"
		;;
	esac
	break
done

# Prepare for backups.
"${0%backup*}backup-prepare"

# Create backups.
set -- "${@}" --
if [ -f "${dir}/conf/src-prefix" ]
then
	src_prefix=$( grep -- '^[^#]' "${dir}/conf/src-prefix" )
elif [ -f "${dir}/conf/src-host" ]
then
	src_prefix=$( grep -- '^[^#]' "${dir}/conf/src-host" ):
else
	src_prefix=
fi
while read arg
do
	case ${arg} in
	'' | '#'* ) continue ;;
	esac
	set -- "${@}" "${src_prefix}${arg}"
done < "${dir}/conf/src-list"
"${0%backup*}backup-create" "${@}"

# Delete old backup directories.
"${0%backup*}backup-purge"
