#! /bin/sh -Ceu
###########################################################################
# backup 0.0.20211031
#
# Copyright (C) 2010-2021 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
# Try to be nice.
{
	ionice -c 3  -p "${$}"
	renice -n 99 -p "${$}"
} > /dev/null 2>&1 || :

# Locate the script.
me=$( command -v -- "${0}" || ls -d -- "${0}" )
me_dir=$( dirname -- "${me}" )
case ${me_dir} in
. ) dir=.. ;;
* ) dir=$( dirname -- "${me_dir}" ) ;;
esac

basename=${0##*[\\/]}
short_description='create a new backup directory and do related tasks'
valid=[:alnum:]_.-


# Parse options.
while :
do
	case ${1-} in
	--help | -h ) exec fmt -s -w "${COLUMNS:-$( tput cols )}" << __HELP__
Usage: ${basename} [<RSYNC-OPTION>]...
 or:   ${basename} <OPTION>...

Prepare for backups by executing preparation scripts, \
read backup sources from configuration files, \
create a new backup directory from the backup sources using rsync(1) and \
then delete old backup directories \
based on pattern matching and ages. \
For details, see \
${basename%backup*}backup-prepare(1), \
${basename%backup*}backup-sources(1) and \
${basename%backup*}backup-purge(1).

Options:
    -h, --help[=<FORMAT>]
        Show this help message and exit.
    -V, --version
        Show version information and exit.

Rsync options:
$( exec rsync --help | exec sed '
	/^ *-/,/^$/!d
	/^ *--help/d
	/^ *--version/d
	/./!d
	s/^ */        /
	s/,-/, -/g
	/^ *-/{
		s//    -/
		s/\([^, ]\)  */\1\
        /
	}
' )

Files:
    ${dir}/<YEAR>
        A yearly backup directory.
    ${dir}/<YEAR>[-]<MONTH>
        A monthly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>
        A weekly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>
        An hourly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>
        A minutely backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>[:]<SECOND>
        A secondly backup directory.
    ${dir}/latest
        A symbolic link to the latest backup directory.
    ${dir}/conf/backup-src-host
        An optional configuration file \
used by ${basename%backup*}backup-sources(1) \
containing the backup source host \
to be used \
if the backup source host is not specified \
in the conf/backup-src-list configuration file or \
in the conf/backup-src-prefix configuration file. \
The file must contain a line having the following form:
            [<USER>@]<HOST>
    ${dir}/conf/backup-src-list
        A configuration file \
used by ${basename%backup*}backup-sources(1) \
containing the backup sources \
to be copied to a newly created backup directory \
when creating a new backup. \
The file must contain operand lines having any the following forms:
            <SRC>
                A local source to be copied to a newly created backup directory.
            [<USER>@]<HOST>:<SRC>
                A remote shell source to be copied to a newly created backup directory.
            [<USER>@]<HOST>::<SRC>
                A rsync daemon source to be copied to a newly created backup directory.
            rsync://[<USER>@]<HOST>[:<PORT>]/<SRC>
                A rsync daemon source to be copied to a newly created backup directory.
        These operands will be passed \
to the ${basename%backup*}backup-create(1) tool. \
Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/backup-src-prefix
        An optional configuration file \
used by ${basename%backup*}backup-sources(1) \
containing the backup source prefix \
to be used \
if the backup source prefix is not specified \
in the conf/backup-src-list configuration file. \
The file must contain a line having one of the following forms:
            <BASE-DIR>
                A local base directory.
            [<USER>@]<HOST>:[<BASE-DIR>]
                A remote shell host and an optional base directory.
            [<USER>@]<HOST>::[<MODULE>[/<BASE-DIR>]]
                A rsync daemon host and an optional module and base directory.
            rsync://[<USER>@]<HOST>[:<PORT>][/<MODULE>[/<BASE-DIR>]]
                A rsync daemon host and an optional module and base directory.
    ${dir}/conf/backup-src-user
        An optional configuration file \
used by ${basename%backup*}backup-sources(1) \
containing the backup source user \
to be used \
if only the backup source host but not the user is specified \
in the conf/backup-src-host configuration file. \
The file must contain a line having the following form:
            <USER>
    ${dir}/conf/create-config
        An optional configuration file \
used by ${basename%backup*}backup-create-rsync(1) \
used by ${basename%backup*}backup-create(1) \
used by ${basename%backup*}backup-sources(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1) \
when creating a new backup directory.
    ${dir}/conf/dump-config
        An optional configuration file \
used by some ${dir}/conf/pre.d/*-dump scripts \
used by ${basename%backup*}backup-prepare(1) \
containing configuration variable assignments.
    ${dir}/conf/pre.d/
        An optional directory \
used by ${basename%backup*}backup-prepare(1) \
containing scripts \
which are executed in lexical order of names \
when preparing for backups. \
The names of the files must consist of only characters \
matching the pattern [${valid}].
    ${dir}/conf/purge-list
        An optional configuration file \
used by ${basename%backup*}backup-purge(1) \
containing patterns and ages \
which override the default ones. \
The file must contain operand lines having the following form:
            <PATTERN>=<DAYS>
        Empty lines and comment lines (starting with a "#") are allowed, too. \
Backup directories matching <PATTERN> are deleted \
if they are over <DAYS> days old.
    ${dir}/conf/rsh
        An optional script \
to be used as a remote shell instead of the plain ssh(1). \
This script can be used for setting identity files and proxy commands, \
for instance.
    ${dir}/conf/rsync-config
        An optional configuration file \
used by ${basename%backup*}backup-rsync(1) \
used by ${basename%backup*}backup-copy-rsync(1) and ${basename%backup*}backup-create-rsync(1) \
used by ${basename%backup*}backup-copy(1) and ${basename%backup*}backup-create(1) \
used by ${basename%backup*}backup-mirror-sources(1) and ${basename%backup*}backup-sources(1) \
used by ${basename}(1) and ${basename%backup*}backup-mirror(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1).
    ${dir}/conf/tag-formats
        An optional configuration file \
used by ${basename%backup*}backup-create(1) \
used by ${basename%backup*}backup-sources(1) \
containing date formats \
to be used \
when constructing a backup directory name for a new backup. \
Empty lines and comment lines (starting with a "#") are allowed, too. \
Each date format is tried in turn in order specified \
until a non-existing backup directory is found.
    ${dir}/tmp/
        A temporary directory to be used for creating a new backup directory.
    ${dir}/tools/${basename%backup*}backup-prepare
        Used for preparing for backups by executing preparation scripts.
    ${dir}/tools/${basename%backup*}backup-purge
        Used for deleting old backup directories \
based on pattern matching and ages.
    ${dir}/tools/${basename%backup*}backup-sources
        Used for creating a new backup directory from backup sources \
using rsync(1).
    $( command -v -- rsync )
        A fast and extraordinarily versatile file copying tool. \
See also rsync(1).
    $( command -v -- ssh )
        A remote login program. \
See also ssh(1).
    <SOURCE-DIRECTORY>/.backup-filter
        An optional per-directory rsync(1) filter merge-file \
which can be used for excluding files from backups. \
Empty lines and comment lines (starting with a "#") are allowed, too.
__HELP__
		;;
	--help=help2man )
		COLUMNS=2500 exec "${0}" --help \
		| exec sed \
			-e '/^    [^ ]/!b'	\
			-e '/[^ ]  /b'		\
			-e 'N'			\
			-e 's/\n        -/  ​-/'	\
			-e 's/\n        /  /'	\
			-e 'P'			\
			-e 'D'
		exit
		;;
	--help=man )
		exec "${0}" --help=troff \
		| exec man -l -- -
		exit
		;;
	--help=troff )
		exec help2man -h --help=help2man -L en_US.UTF-8 -N -n "${short_description}" -- "${0}" \
		| exec sed \
			-e 's|\([[:alnum:]\\-][[:alnum:]\\-]*\)[(]\([[:digit:]]*\)[)]|\\fB\1\\fR(\2)|g'
		exit
		;;
	--version | -V )
		exec sed -n \
			-e '/^[^#]/q'				\
			-e "3s/^# [^ ]* /# ${basename} /"	\
			-e 's/^#\( \(.*\)\)*$/\2/p'		\
			-e '/^##/{2!q;}'			\
			-- "${me}"
		;;
	esac
	break
done

# Prepare for backups.
"${0%backup*}backup-prepare"

# Create a new backup directory from backup sources.
"${0%backup*}backup-sources" "${@}"

# Delete old backup directories.
"${0%backup*}backup-purge"
