#! /bin/sh -Ceu
# backup-create-rsync - a backup creation oriented file-copying tool
###########################################################################
# backup-create-rsync 0.0.20220904
#
# Copyright (C) 2010-2021 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
# Try to be nice.
{
	ionice -c 3  -p "${$}"
	renice -n 99 -p "${$}"
} > /dev/null 2>&1 || :

# Locate the script.
me=$( command -v -- "${0}" || ls -d -- "${0}" )
me_base=$( basename -- "${me}" )
me_dir=$( dirname -- "${me}" )
case ${me_dir} in
.  ) dir=.. ;;
.. ) dir=../.. ;;
*. ) dir=$( cd -- "${me_dir}/.." && pwd ) ;;
*  ) dir=$( dirname -- "${me_dir}" ) ;;
esac

valid='[:alnum:]_.-'


# Parse options.
while :
do
	case ${1-} in
	--help | -h )
		COLUMNS=${COLUMNS:-$( tput cols 2> /dev/null || : )}
		exec fmt -s ${COLUMNS:+ -w "${COLUMNS}" } << __HELP__ \
		| exec sed -e '/\\$/{N;s/\\\n  *//;}'; exit
Usage: \\
           ${me_base} [<RSYNC-OPTION>]... <SRC>... [<DEST>]
 or:   \\
           ${me_base} [<RSYNC-OPTION>]... <BASE-DIR>/./[<SRC>]... [<DEST>]
 or:   \\
           ${me_base} [<RSYNC-OPTION>]... [<USER>@]<HOST>:<SRC>... [<DEST>]
 or:   \\
           ${me_base} [<RSYNC-OPTION>]... [<USER>@]<HOST>:<BASE-DIR>/./[<SRC>]... [<DEST>]
 or:   \\
           ${me_base} [<RSYNC-OPTION>]... [<USER>@]<HOST>::<MODULE>[/[<SRC>]]... [<DEST>]
 or:   \\
           ${me_base} [<RSYNC-OPTION>]... [<USER>@]<HOST>::<MODULE>/<BASE-DIR>/./[<SRC>]... [<DEST>]
 or:   \\
           ${me_base} [<RSYNC-OPTION>]... rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>[/[<SRC>]]... [<DEST>]
 or:   \\
           ${me_base} [<RSYNC-OPTION>]... rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>/<BASE-DIR>/./[<SRC>]... [<DEST>]
 or:   \\
           ${me_base} <OPTION>...

Copy files \
using ${me_base%backup*}backup-rsync(1) and thus rsync(1) \
with backup creation related options.

Options:
    -h, --help[=<FORMAT>]
        Show this help message and exit.
    -V, --version
        Show version information and exit.

Rsync options:
$( exec rsync --help | exec sed '
	/^ *-/,/^$/!d
	/^ *--help/d
	/^ *--version/d
	/./!d
	s/^ */        /
	s/,-/, -/g
	/^ *-/{
		s//    -/
		s/\([^, ]\)  */'"\1\\
        "'/
	}
' )

Operands:
    <SRC>
        A local source to be copied.
    <BASE-DIR>/./[<SRC>]
        A local source to be copied without the base directory.
    [<USER>@]<HOST>:<SRC>
        A remote shell source to be copied.
    [<USER>@]<HOST>:<BASE-DIR>/./[<SRC>]
        A remote shell source to be copied without the base directory.
    [<USER>@]<HOST>::<MODULE>[/[<SRC>]]
        An rsync daemon source to be copied.
    [<USER>@]<HOST>::<MODULE>/<BASE-DIR>/./[<SRC>]
        An rsync daemon source to be copied without the base directory.
    rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>[/[<SRC>]]
        An rsync daemon source to be copied.
    rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>/<BASE-DIR>/./[<SRC>]
        An rsync daemon source to be copied without the base directory.
    <DEST>
        A destination.

Files:
    ${dir}/conf/create-config
        An optional configuration file \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1) \
when creating a new backup directory.
    ${dir}/conf/create-config.d
        An optional directory \
containing configuration files \
similar to the ${dir}/conf/create-config configuration file \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1) \
when creating a new backup directory. \
The names of the files must consist of only characters \
matching the pattern [${valid}].
    ${dir}/conf/rsh
        An optional script \
to be used as a remote shell instead of the plain ssh(1). \
This script can be used for setting identity files and proxy commands, \
for instance.
    ${dir}/conf/rsync-config
        An optional configuration file \
used by ${me_base%backup*}backup-rsync(1) \
used by ${me_base%backup*}backup-copy-rsync(1) and ${me_base}(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1).
    ${dir}/conf/rsync-config.d
        An optional directory \
used by ${me_base%backup*}backup-rsync(1) \
used by ${me_base%backup*}backup-copy-rsync(1) and ${me_base}(1) \
containing configuration files \
similar to the ${dir}/conf/rsync-config configuration file \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1). \
The names of the files must consist of only characters \
matching the pattern [${valid}].
    ${dir}/tools/${me_base%backup*}backup-rsync
        Used for copying files using rsync(1).
    <SOURCE-DIRECTORY>/.backup-filter
        An optional per-directory rsync(1) filter merge-file \
which can be used for excluding files from backups. \
Empty lines and comment lines (starting with a "#") are allowed, too.

See also:
    ${me_base%backup*}backup-create(1),
    ${me_base%backup*}backup-help(1),
    ${me_base%backup*}backup-rsync(1)

    rsync(1),
    ssh(1)

    Home page <https://github.Eero.Häkkinen.fi/rsync-backup/>
__HELP__
		;;
	--help=* | --version | -V )
		export BACKUP_TOOL="${0}"
		exec "${0%backup*}backup-help" "${1}"
		;;
	esac
	break
done

# Execute.
exec "${0%backup*}backup-rsync" --backup-config-name='create' "${@}"
