#! /bin/sh -Ceu
# backup-nice - run a backup command nicely
###########################################################################
# backup-nice 0.0.20220615
#
# Copyright (C) 2018 - 2022 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
# Try to be nice.
{
	ionice -c 3  -p "${$}"
	renice -n 99 -p "${$}"
} > /dev/null 2>&1 || :

# Locate the script.
me=$( command -v -- "${0}" || ls -d -- "${0}" )
me_base=$( basename -- "${me}" )











# Parse options.
while :
do
	case ${1-} in
	--help | -h )
		COLUMNS=${COLUMNS:-$( tput cols 2> /dev/null || : )}
		exec fmt -s ${COLUMNS:+ -w "${COLUMNS}" } << __HELP__ \
		| exec sed -e '/\\$/{N;s/\\\n  *//;}'; exit
Usage: \\
           ${me_base} <COMMAND> [<ARG>]...
 or:   \\
           ${me_base} <OPTION>...

Run a backup command \
with idle I/O priority (whose impact on normal system activity should be zero), \
with an adjusted niceness (which affect process scheduling) and \
with minimized effect on file system cache \
provided that the commands ionice(1), nice(1) and nocache(1) are available.

Options:
    -h, --help[=<FORMAT>]
        Show this help message and exit.
    -V, --version
        Show version information and exit.

Operands:
    <COMMAND> [<ARG>]...
        A backup command to be executed.

See also:
    ${me_base%backup*}backup-help(1),
    ${me_base%backup*}backup-prepare(1),
    ${me_base%backup*}backup-rsync(1)

    ionice(1),
    nice(1),
    nocache(1)

    Home page <https://github.Eero.Häkkinen.fi/rsync-backup/>
__HELP__
		;;
	--help=* | --version | -V )
		export BACKUP_TOOL="${0}"
		exec "${0%backup*}backup-help" "${1}"
		;;
	--  ) shift; break ;;
	-?* ) "getopts${-##*}" '' OPT "${@}"; exit 1 ;;
	*   ) break ;;
	esac
done

# Execute.
IONICE=${IONICE-$( command -v -- ionice || : )}
NICE=${NICE-$( command -v -- nice || : )}
NOCACHE=${NOCACHE-$( command -v -- nocache || : )}
exec \
	${IONICE:+	"${IONICE}" -c 3 --	} \
	${NICE:+	"${NICE}" -n 99 --	} \
	${NOCACHE:+	"${NOCACHE}" -n 2 --	} \
	"${@}"
