#! /bin/sh -Ceu
###########################################################################
# backup-mirror-sources 0.0.20211107
#
# Copyright (C) 2010-2021 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
# Try to be nice.
{
	ionice -c 3  -p "${$}"
	renice -n 99 -p "${$}"
} > /dev/null 2>&1 || :

# Locate the script.
me=$( command -v -- "${0}" || ls -d -- "${0}" )
me_dir=$( dirname -- "${me}" )
case ${me_dir} in
. ) dir=.. ;;
* ) dir=$( dirname -- "${me_dir}" ) ;;
esac

basename=${0##*[\\/]}
short_description='copy backup directories from mirror sources'



# Parse options.
while :
do
	case ${1-} in
	--help | -h )
		COLUMNS=${COLUMNS:-$( tput cols 2> /dev/null || : )}
		exec fmt -s ${COLUMNS:+ -w "${COLUMNS}" } << __HELP__
Usage: ${basename} [<RSYNC-OPTION>]...
 or:   ${basename} <OPTION>...

Read mirror sources from configuration files and \
copy backup directories from the mirror sources using rsync(1). \
For details, see \
the Files section and \
${basename%backup*}backup-copy(1).

Options:
    -h, --help[=<FORMAT>]
        Show this help message and exit.
    -V, --version
        Show version information and exit.

Rsync options:
$( exec rsync --help | exec sed '
	/^ *-/,/^$/!d
	/^ *--help/d
	/^ *--version/d
	/./!d
	s/^ */        /
	s/,-/, -/g
	/^ *-/{
		s//    -/
		s/\([^, ]\)  */\1\
        /
	}
' )

Files:
    ${dir}/<YEAR>
        A yearly backup directory.
    ${dir}/<YEAR>[-]<MONTH>
        A monthly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>
        A weekly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>
        An hourly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>
        A minutely backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>[:]<SECOND>
        A secondly backup directory.
    ${dir}/latest
        A symbolic link to the latest backup directory.
    ${dir}/conf/copy-config
        An optional configuration file \
used by ${basename%backup*}backup-copy-rsync(1) \
used by ${basename%backup*}backup-copy(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1) \
when copying a backup directory.
    ${dir}/conf/mirror-src-base
        An optional configuration file \
containing the mirror source base directory \
to be used to augment \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <BASE-DIR>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-host
        An optional configuration file \
containing the mirror source host \
to be used to augment \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <HOST>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-list
        A configuration file \
containing the mirror sources \
to be copied to newly created backup directories \
when copying backup directories. \
The file must contain operand lines having any the following forms:
            <SRC>/[.]
                A local directory containing backup directories to be copied.
            <SRC>
                A local backup directory to be copied.
            [<USER>@]<HOST>:<SRC>/[.]
                A remote directory containing backup directories to be copied via a remote shell.
            [<USER>@]<HOST>:<SRC>
                A remote backup directory to be copied via a remote shell.
            [<USER>@]<HOST>::<MODULE>[/<SRC>]/[.]
                A remote directory containing backup directories to be copied via an rsync daemon.
            [<USER>@]<HOST>::<MODULE>/<SRC>
                A remote backup directory to be copied via an rsync daemon.
            rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>[/<SRC>]/[.]
                A remote directory containing backup directories to be copied via an rsync daemon.
            rsync://[<USER>@]<HOST>[:<PORT>]/<MODULE>/<SRC>
                A remote backup directory to be copied via an rsync daemon.
        The operands specifying directories containing backup directories \
will be passed \
to the ${basename%backup*}backup-rsync(1) tool. \
The backup directories within these directories \
as well as the operands specifying backup directories \
will be passed \
to the ${basename%backup*}backup-copy(1) tool. \
Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-module
        An optional configuration file \
containing the mirror source module \
to be used to augment \
the mirror source host specified in the conf/mirror-src-host configuration file and \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <MODULE>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-port
        An optional configuration file \
containing the mirror source port \
to be used to augment \
the mirror source host specified in the conf/mirror-src-host configuration file, \
the mirror source module specified in the conf/mirror-src-module configuration file and \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <PORT>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-prefix
        An optional configuration file \
containing the mirror source prefix \
to be used to augment \
the mirror sources specified in the conf/mirror-src-list configuration file. \
The file must contain a line having one of the following forms:
            <BASE-DIR>
                A local base directory.
            [<USER>@]<HOST>:[<BASE-DIR>]
                A remote shell host and an optional base directory.
            [<USER>@]<HOST>::[<MODULE>[/<BASE-DIR>]]
                An rsync daemon host and an optional module and base directory.
            <USER>@
                A remote shell or an rsync daemon user.
            rsync://[<USER>@]<HOST>[:<PORT>][/<MODULE>[/<BASE-DIR>]]
                An rsync daemon host and an optional module and base directory.
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/mirror-src-user
        An optional configuration file \
containing the mirror source user \
to be used to augment \
the mirror source host specified in the conf/mirror-src-host configuration file and \
the mirror sources specified in the conf/mirror-src-list configuration file \
if the conf/mirror-src-prefix configuration file does not exist. \
The file must contain a line having the following form:
            <USER>
        Empty lines and comment lines (starting with a "#") are allowed, too.
    ${dir}/conf/rsh
        An optional script \
to be used as a remote shell instead of the plain ssh(1). \
This script can be used for setting identity files and proxy commands, \
for instance.
    ${dir}/conf/rsync-config
        An optional configuration file \
used by ${basename%backup*}backup-rsync(1) \
used by ${basename%backup*}backup-copy-rsync(1) and ${basename%backup*}backup-create-rsync(1) \
used by ${basename%backup*}backup-copy(1) and ${basename%backup*}backup-create(1) \
used by ${basename}(1) and ${basename%backup*}backup-sources(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1).
    ${dir}/tmp/
        A temporary directory to be used for copying backup directories.
    ${dir}/tools/${basename%backup*}backup-copy
        Used for copying backup directories from mirror sources using rsync(1).
    $( command -v -- rsync )
        A fast and extraordinarily versatile file copying tool. \
See also rsync(1).
    $( command -v -- ssh )
        A remote login program. \
See also ssh(1).
__HELP__
		;;
	--help=help2man )
		COLUMNS=2500 exec "${0}" --help \
		| exec sed \
			-e '/^    [^ ]/!b'	\
			-e '/[^ ]  /b'		\
			-e 'N'			\
			-e 's/\n        -/  ​-/'	\
			-e 's/\n        /  /'	\
			-e 'P'			\
			-e 'D'
		exit
		;;
	--help=man )
		exec "${0}" --help=troff \
		| exec man -l -- -
		exit
		;;
	--help=troff )
		cat << '__TROFF__'
.if '\*[.T]'html' \{\
.HEAD "<link href=""groff.css"" rel=""stylesheet"" type=""text/css"" />"
.HEAD "<meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />"
.HX 0
.\}
__TROFF__
		exec help2man -h --help=help2man -L en_US.UTF-8 -N -n "${short_description}" -- "${0}" \
		| exec sed \
			-e 's|\([[:alnum:]\\-][[:alnum:]\\-]*\)[(]\([[:digit:]]*\)[)]|\\fB\1\\fR(\2)|g'
		exit
		;;
	--help=* )
		exec "${0}" --help=troff \
		| exec man -l -T"${1#*=}" -- -
		exit
		;;
	--version | -V )
		exec sed -n \
			-e '/^[^#]/q'				\
			-e "3s/^# [^ ]* /# ${basename} /"	\
			-e 's/^#\( \(.*\)\)*$/\2/p'		\
			-e '/^##/{2!q;}'			\
			-- "${me}"
		;;
	esac
	break
done

# Copy backup directories from mirror sources.
set -- "${@}" --
if [ ! -f "${dir}/conf/mirror-src-prefix" ]
then
	if [ ! -f "${dir}/conf/mirror-src-base" ]
	then
		unset src_base
	else
		src_base=$(
			grep -- '^[^#]' "${dir}/conf/mirror-src-base"
			)
		src_base=${src_base%/}/
	fi
	if [ ! -f "${dir}/conf/mirror-src-host" ]
	then
		src_prefix=${src_base-}
	else
		src_prefix=$( grep -- '^[^#]' "${dir}/conf/mirror-src-host" )
		[ ! -f "${dir}/conf/mirror-src-user" ] || src_prefix=$(
			grep -- '^[^#]' "${dir}/conf/mirror-src-user"
			)@${src_prefix}
		if [ ! -f "${dir}/conf/mirror-src-module" ]
		then
			src_prefix=${src_prefix}:${src_base-}
		else
			src_module=$(
				grep -- '^[^#]' "${dir}/conf/mirror-src-module"
				)
			if [ ! -f "${dir}/conf/mirror-src-port" ]
			then
				src_prefix=${src_prefix}::${src_module}${src_base+/${src_base#/}}
			else
				src_port=$(
					grep -- '^[^#]' "${dir}/conf/mirror-src-port"
					)
				src_prefix=rsync://${src_prefix}:${src_port}/${src_module}${src_base+/${src_base#/}}
			fi
		fi
	fi
else
	src_prefix=$( grep -- '^[^#]' "${dir}/conf/mirror-src-prefix" )
fi
while read src
do
	case ${src} in
	'' | '#'* ) continue ;;
	esac
	case ${src_prefix} in
	*/ ) src=${src#/} ;;
	esac
	set -- "${@}" "${src_prefix}${src}"
done < "${dir}/conf/mirror-src-list"
exec "${0%backup*}backup-copy" "${@}"
