#! /bin/sh -Ceu
###########################################################################
# backup-copy 0.0.20200510
#
# Copyright (C) 2010-2020 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
# Try to be nice.
{
	ionice -c 3  -p "${$}"
	renice -n 99 -p "${$}"
} > /dev/null 2>&1 || :

# Locate the script.
me=$( which -- "${0}" || ls -d -- "${0}" )
dir=$( dirname -- "${me}" )
case ${dir} in
. ) dir=.. ;;
* ) dir=$( dirname -- "${dir}" ) ;;
esac

basename=${0##*[\\/]}
short_description='copy backup directories'



# Parse options.
while :
do
	case ${1-} in
	--help | -h ) exec fmt -s -w "${COLUMNS:-$( tput cols )}" << __HELP__
Usage: ${basename} [<RSYNC-OPTION>]... [[<USER>@]<HOST>:]<SRC>[/[.]]...
 or:   ${basename} [<RSYNC-OPTION>]... [<USER>@]<HOST>::<SRC>[/[.]]...
 or:   ${basename} [<RSYNC-OPTION>]... rsync://[<USER>@]<HOST>[:<PORT>]/<SRC>[/[.]]...
 or:   ${basename} <OPTION>...

Copy backup directories from sources using rsync(1).

A backup directory is copied using the following steps:

  An empty backup directory is created in a temporary directory.

  Files and directories are copied \
from a source backup directory \
to the newly created backup directory \
using rsync(1).

  A new symbolink link to denote the latest backup directory \
is created in a temporary directory.

  The newly created backup directory and \
the newly created symbolink link \
are moved to the final location.

Disk usage is minimised and \
the transfer is speeded up \
by hard linking files \
from old backup directories \
to newly created backup directories \
whenever possible \
(when files in sources and previous backup directories are identical \
in content and in all preserved attributes).
On the btrfs and s3ql filesystems, \
hard linking \
is not needed and \
is therefore not used \
for disk usage minimisation.

Options:
    -h, --help[=<FORMAT>]
        Show this help message and exit.
    -V, --version
        Show version information and exit.

Rsync options:
$( exec rsync --help | exec sed '
	/^ *-/,/^$/!d
	/ --help/d
	/ --version/d
	/./!d
	s/^ */        /
	s/,-/, -/g
	/^ *-/{
		s//    -/
		s/\([^, ]\) /\1\
/
	}
	P
	D
' )

Operands:
    <SRC>/[.]
        A local directory containing backup directories to be copied.
    <SRC>
        A local backup directory to be copied.
    [<USER>@]<HOST>:<SRC>/[.]
        A remote directory containing backup directories to be copied via a remote shell.
    [<USER>@]<HOST>:<SRC>
        A remote backup directory to be copied via a remote shell.
    [<USER>@]<HOST>::<SRC>/[.]
        A remote directory containing backup directories to be copied via an rsync daemon.
    [<USER>@]<HOST>::<SRC>
        A remote backup directory to be copied via an rsync daemon.
    rsync://[<USER>@]<HOST>[:<PORT>]/<SRC>/[.]
        A remote directory containing backup directories to be copied via an rsync daemon.
    rsync://[<USER>@]<HOST>[:<PORT>]/<SRC>
        A remote backup directory to be copied via an rsync daemon.

Files:
    ${dir}/<YEAR>
        A yearly backup directory.
    ${dir}/<YEAR>[-]<MONTH>
        A monthly backup directory.
    ${dir}/<YEAR>[-]W<WEEK>
        A weekly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]W<WEEK>[-]<DAY>
        A daily backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>
        An hourly backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>
        A minutely backup directory.
    ${dir}/<YEAR>[-]<MONTH>[-]<DAY>T<HOUR>[:]<MINUTE>[:]<SECOND>
        A secondly backup directory.
    ${dir}/latest
        A symbolic link to the latest backup directory.
    ${dir}/conf/copy-config
        An optional configuration file \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1) \
when copying a backup directory.
    ${dir}/conf/rsh
        An optional script \
to be used as a remote shell instead of the plain ssh(1). \
This script can be used for setting identity files and proxy commands, \
for instance.
    ${dir}/conf/rsync-config
        An optional configuration file \
used by ${basename%backup*}backup-rsync(1) \
used by ${basename}(1) and ${basename%backup*}backup-create(1) \
containing long option names (without leading slashes) and \
optional option arguments \
to be passed to rsync(1).
    ${dir}/tmp/
        A temporary directory to be used for copying backup directories.
    ${dir}/tools/${basename%backup*}backup-rsync
        Used for copying files using rsync(1).
    $( which rsync )
        A fast and extraordinarily versatile file copying tool. \
See also rsync(1).
    $( which ssh )
        A remote login program. \
See also ssh(1).
__HELP__
		;;
	--help=help2man )
		COLUMNS=2500 exec "${0}" --help \
		| exec sed \
			-e '/^    [^ ]/!b'	\
			-e '/[^ ]  /b'		\
			-e 'N'			\
			-e 's/\n        /  /'	\
			-e 'P'			\
			-e 'D'
		exit
		;;
	--help=man )
		exec "${0}" --help=troff \
		| exec man -l -- -
		exit
		;;
	--help=troff )
		exec help2man -h --help=help2man -L en_US.UTF-8 -N -n "${short_description}" -- "${0}" \
		| exec sed -e 's/\([[:alnum:]\\-][[:alnum:]\\-]*\)[(]\([[:digit:]]*\)[)]/\\fB\1\\fR(\2)/g'
		exit
		;;
	--version | -V )
		exec sed -n \
			-e '/^[^#]/q'				\
			-e "3s/^# [^ ]* /# ${basename} /"	\
			-e 's/^#\( \(.*\)\)*$/\2/p'		\
			-e '/^##/{2!q;}'			\
			-- "${me}"
		;;
	esac
	break
done

# Find out rsync options requiring an option argument.
rsync_optarg_opts=$( LC_ALL=C exec rsync --help | exec sed '
	/^ *-/,/^$/!d
	s/^ *\(\(-[^(), ]*\(, \)*\)*\).*/\1/
	/=.*/!d
	s///
	s/[, ][, ]*/ /g
' )

# Parse options, option arguments and operands.
unset argtype
for arg
do
	# Parse an option or an option argument.
	case ${argtype-opt}:${arg} in
	opt:-- ) # --
		# Drop the end of options option and operands.
		set -- ${argtype+"${@}"}
		argtype=operand
		continue
		;;
	opt:-?* ) # -<OPT>[...][<OPTARG>], --<OPT>[=<OPTARG>]
		# Keep an option.
		set -- ${argtype+"${@}"} "${arg}"
		case ${arg} in
		--?*=* ) # --<OPT>=<OPTARG>
			argtype=opt
			;;
		--?* ) # --<OPT>
			case " ${rsync_optarg_opts:?} " in
			*[[:space:]]"${arg}"[[:space:]]* ) # --<OPT> <OPTARG>
				argtype=optarg
				;;
			* ) # --<OPT>
				argtype=opt
				;;
			esac
			;;
		* )
			while :
			do
				case " ${rsync_optarg_opts:?} " in
				*[[:space:]]"${arg%"${arg#-?}"}"[[:space:]]* )
					case ${arg} in
					-??* ) # -<OPT><OPTARG>
						argtype=opt
						;;
					* ) # -<OPT> <OPTARG>
						argtype=optarg
						;;
					esac
					;;
				* )
					case ${arg} in
					-??* ) # -<OPT><OPT>[...][<OPTARG>]
						arg=-${arg#-?}
						continue
						;;
					* ) # -<OPT>
						argtype=opt
						;;
					esac
					;;
				esac
				break
			done
			;;
		esac
		continue
		;;
	opt:* ) # <OPERAND>
		# Drop operands.
		set -- ${argtype+"${@}"}
		argtype=operand
		;;
	optarg:* ) # <OPTARG>
		# Keep an option argument.
		set -- "${@}" "${arg}"
		argtype=opt
		continue
		;;
	esac
	# Parse an operand.
	case ${arg} in
	*/ | */. ) # <SRC>/[.]
		# Prepare to create a protected temporary directory.
		mkdir -m go=u-w -p -- \
			"${dir}/tmp" \
			"${dir}/tmp/copy-${$}" \
			"${dir}/tmp/old-copy-${$}"
		rm -fr -- "${dir}/tmp/old-copy-${$}"/*
		mv -f -- "${dir}/tmp/copy"-* "${dir}/tmp/old-copy-${$}/"
		rm -fr -- "${dir}/tmp/old-copy"-*
		# Create a protected temporary directory.
		mkdir -m go= -- "${dir}/tmp/copy-${$}"
		# Find out the backup directories to be copied.
		exclude=$(
			exec ls -- "${dir}/" \
			| exec sed -n -e '/./s|^[[:digit:][:punct:]TW]*$|--exclude=/&/|p'
			)
		"${0%backup*}backup-rsync" \
			--backup-config-name='copy'		\
			--exclude='/*[![:digit:][:punct:]TW]*'	\
			--exclude='/*/*'			\
			${exclude}				\
			"${@}"					\
			--include='/[[:digit:]]*/'		\
			--exclude='/*'				\
			--exclude='/*/*'			\
			-- "${arg%/*}/./" "${dir}/tmp/copy-${$}/"
		# Copy the backup directories.
		exec ls -rt -- "${dir}/tmp/copy-${$}/" | {
			while read tag
			do
				case ${tag} in
				*[![:digit:][:punct:]TW]* ) ;;
				[[:digit:]]* ) "${0%backup*}backup-create" \
					--backup-config-name='copy'	\
					--backup-tag-name="${tag}"	\
					"${@}"				\
					-- "${arg%/*}/${tag}/./" ;;
				esac
			done
		}
		# Clean up.
		rm -fr -- "${dir}/tmp/copy-${$}"
		;;
	* ) # <SRC>
		# Copy a backup directory.
		tag=$( basename -- "${arg}" )
		"${0%backup*}backup-create" \
			--backup-config-name='copy'	\
			--backup-tag-name="${tag}"	\
			"${@}"				\
			-- "${arg}/./"
		;;
	esac
done
