#! /bin/sh -Ceu
###########################################################################
# backup-nologin 0.0.20191002
#
# Copyright (C) 2019 Eero Häkkinen <Eero+rsync-backup@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
case ${SSH_ORIGINAL_COMMAND:++},${#},${1-} in
+,2,-c )
	case ${2} in
	"${0%backup-nologin}backup-rsync "* )
		exec "${0%backup-nologin}backup-rsync" ${2#"${0%backup-nologin}backup-rsync "}
		;;
	"exec ${0%backup-nologin}backup-rsync "* )
		exec "${0%backup-nologin}backup-rsync" ${2#"exec ${0%backup-nologin}backup-rsync "}
		;;
	esac
	;;
esac
exec /usr/sbin/nologin "${@}"
