#! /bin/sh -Ceu

# A sample conf/rsh file
# ======================

# Locate the script.
me=$( command -v -- "${0}" || ls -d -- "${0}" )
me_base=$( basename -- "${me}" )
me_dir=$( dirname -- "${me}" )
me_dir=$( cd -- "${me_dir}" && pwd )
case ${me_dir} in */.misc/*  ) me_dir=/${me_dir#*/.misc/} ;; esac
case ${me_dir} in */.r[ow]/* ) me_dir=${me_dir%%/.r[ow]/*}/${me_dir#*/.r[ow]/} ;; esac

# Use identity files.
for identity_file in "${me_dir}/ssh"/id_*
do
	case ${identity_file} in
	*.pub ) continue ;;
	esac
	[ ! -f "${identity_file}" ] || set -- \
		-i "${identity_file}" \
		"${@}"
done

# Use some extra options.
[ ! -f "${me_dir}/ssh/known_hosts" ] || set -- \
	-o UserKnownHostsFile="${me_dir}/ssh/known_hosts" \
	"${@}"
set -- \
	-o ClearAllForwardings=yes \
	-o StrictHostKeyChecking=yes \
	-o VerifyHostKeyDNS=yes \
	"${@}"
[ ! -f "${me_dir}/ssh/config" ] || set -- \
	-F "${me_dir}/ssh/config" \
	"${@}"

# Use a proxy command for root.
case " ${*} " in
*' -l root '* )
	case ${SUDO_USER:++} in
	+ ) rsh=ssh ;;
	* ) rsh=${me_dir}/${me_base} ;;
	esac
	set -- \
		-o ProxyCommand="\
'${rsh}' -l '${SUDO_USER:-backup}' -p '%p' -W 'localhost:%p' -- '%h'\
" \
		"${@}"
	;;
esac

# Execute SSH.
set -- ssh "${@}"
uid=$( id -u )
case ${uid}," ${*} " in
0,*' -l backup '* )
	# Drop privileges.
	unset LD_PRELOAD
	set -- setpriv \
		--inh-caps='-all' \
		--init-groups \
		--regid='backup' \
		--reset-env \
		--reuid='backup' \
		-- env -- \
			SHELL='/bin/sh' \
			"${@}"
	;;
esac
cd -- / && exec "${@}"
